### ISSUE TITLE
Create roadmap

### ISSUE THREAD

**Issue by Linkinlog** [Linkinlog/.dotfiles#8]
To showcase what we did and are doing. For ex
- [ ] Create update script that will periodically run to keep envs in sync 
- [ ] expand / confirm use on other distros and Mac
- [ ] make sure it runs on already configured systems
